import { NextResponse } from "next/server";
import { headers } from "next/headers";
import { eq } from "drizzle-orm";
import { auth } from "@/lib/auth";
import { db } from "@/db";
import { article } from "@/db/articles-schema";

const TOTAL_DURATION_MS = 30000;
const PROGRESS_STEPS = [
	"Queued",
	"Analyzing prompt",
	"Planning outline",
	"Generating draft",
	"Polishing",
	"Finalizing",
];

const getSession = async () =>
	auth.api.getSession({
		headers: await headers(),
	});

const getTimestampMs = (value: Date | number) =>
	value instanceof Date ? value.getTime() : value;

const buildCompletedContent = (inputJson: string) => {
	try {
		const parsed = JSON.parse(inputJson) as {
			prompt?: { description?: string };
		};
		const description = parsed?.prompt?.description?.trim();
		const title =
			description && description.length > 0
				? description.slice(0, 80)
				: "Untitled Article";

		const bodyMarkdown = `# ${title}\n\n## Introduction\n\n${description ?? "This is a demo article generated by the system."}\n\n## Key Points\n\n- Point one\n- Point two\n- Point three\n\n## Conclusion\n\nThanks for reading!`;

		return {
			title,
			bodyMarkdown,
		};
	} catch {
		return {
			title: "Untitled Article",
			bodyMarkdown:
				"# Untitled Article\n\n## Introduction\n\nThis is a demo article generated by the system.",
		};
	}
};

export async function GET(
	_request: Request,
	{ params }: { params: Promise<{ articleId: string }> },
) {
	const session = await getSession();
	if (!session) {
		return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
	}

	const { articleId } = await params;
	const [record] = await db
		.select()
		.from(article)
		.where(eq(article.id, articleId))
		.limit(1);

	if (!record || record.userId !== session.user.id) {
		return NextResponse.json({ error: "Not found" }, { status: 404 });
	}

	const createdAtMs = getTimestampMs(record.createdAt);
	const elapsedMs = Math.max(0, Date.now() - createdAtMs);
	const percent = Math.min(
		100,
		Math.round((elapsedMs / TOTAL_DURATION_MS) * 100),
	);
	const stepIndex = Math.min(
		PROGRESS_STEPS.length - 1,
		Math.floor((elapsedMs / TOTAL_DURATION_MS) * PROGRESS_STEPS.length),
	);

	if (record.status !== "completed" && percent >= 100) {
		const generated = buildCompletedContent(record.inputJson);
		const coverImageUrl =
			record.coverImageUrl ??
			"https://placehold.co/1200x675/png?text=Generated+Cover";

		await db
			.update(article)
			.set({
				status: "completed",
				title: generated.title,
				bodyMarkdown: generated.bodyMarkdown,
				coverImageUrl,
			})
			.where(eq(article.id, record.id));

		record.status = "completed";
		record.title = generated.title;
		record.bodyMarkdown = generated.bodyMarkdown;
		record.coverImageUrl = coverImageUrl;
	}

	return NextResponse.json({
		article: {
			id: record.id,
			status: record.status,
			title: record.title,
			bodyMarkdown: record.bodyMarkdown,
			coverImageUrl: record.coverImageUrl,
			createdAt: record.createdAt,
			updatedAt: record.updatedAt,
			errorMessage: record.errorMessage,
		},
		progress: {
			percent,
			phase: PROGRESS_STEPS[stepIndex],
			steps: PROGRESS_STEPS.map((label, index) => ({
				label,
				status:
					index < stepIndex
						? "done"
						: index === stepIndex
							? "active"
							: "pending",
			})),
		},
	});
}
